### ISSUE TITLE
bad running time

### ISSUE THREAD

**Issue by littlecay** [TracelessLe/OpenPose.PyTorch#1]
I met a problem. The model could only process about 1fps, and after debug, I saw             
Mconv7_stage6_L1 = Mconv7_stage6_L1.cpu().numpy()
Mconv7_stage6_L2 = Mconv7_stage6_L2.cpu().numpy()
take a lot of time, any idea of how to solve this?

**Comment by TracelessLe** [comment]
> I met a problem. The model could only process about 1fps, and after debug, I saw Mconv7_stage6_L1 = Mconv7_stage6_L1.cpu().numpy() Mconv7_stage6_L2 = Mconv7_stage6_L2.cpu().numpy() take a lot of time, any idea of how to solve this?

1. If your input image resolution is large, you can resize it. 
2. If you have confirmed that `.cpu().numpy()` spend a lot of time, try to use some GPU coding techniques such as using pinned memory to reduce DtoH time.
